[package]
name = "examples"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]
edition = "2018"

[dependencies]
winit = "0.19"
image = "0.10.4"
ash = "0.29.0"

[profile.release]
debug = true